WARNING  pytest_result_log:plugin.py:122 ------------Start: testcases/test_comment_news.py::test_comment_succ------------
WARNING  pytest_result_log:plugin.py:128 -------------End: testcases/test_comment_news.py::test_comment_succ-------------